### PR TITLE
Fix newlines replaced by too many HTML line breaks

### LINKED ISSUE #771: Too many new lines are added when pasting plain text in the jodit editor
**Jodit Version:**  3.12.2

**Browser:**  Chrome
**OS:**  Windows
**Is React App:**  False

**Code**

Seems that my latest fix https://github.com/xdan/jodit/pull/770 introduces too many new lines.

I'm pasting this snippet into the editor.

```
This text should be

on different

lines
```

**Expected behavior:**

I'd expect two br tags after each line so the resulting output in the WYSIWYG editor is the same as the original snippet you paste.

**Actual behavior:**

Instead of two br tags 4 br tags are generated.

### PR DESCRIPTION
**Pull request by lievenjanssen**
Fixes https://github.com/xdan/jodit/issues/771

### CODE REVIEW

File: src/core/helpers/html/nl2br.ts [hunk 1]
```diff
@@ -12,5 +12,5 @@
  *  Inserts HTML line breaks before all newlines in a string
  */
 export function nl2br(html: string): string {
-	return html.replace(/[\n\r]/g, '<br/>');
+	return html.replace(/\r\n|\r|\n/g, '<br/>');
```
Comment (xdan) [inline src/core/helpers/html/nl2br.ts:15]: Need tests for this, and may be need \n\r too =)

Comment (lievenjanssen) [reply src/core/helpers/html/nl2br.ts:15]: \n\r shouldn't be necessary, see:

There are three different types of line breaks, all originally unique to the major operating systems: Windows/DOS, Macintosh, and Unix. A document using Mac line breaks would look horrid on a Windows system, and a document using Windows line breaks on Unix also wouldn’t be interpreted correctly. The cause for this is how the line break is actually created. The Mac, by default, uses a single carriage return (<CR>), represented as \r. Unix, on the other hand, uses a single linefeed (<LF>), \n. Windows goes one step further and uses both, creating a (<CRLF>) combination, \r\n.

https://www.oreilly.com/library/view/mac-os-x/0596004605/ch01s06.html#:~:text=There%20are%20three%20different%20types%20of%20line%20breaks%2C%20all,and%20uses%20both%2C%20creating%20a%20(%3CCRLF%3E)%20combination%2C%20%5Cr%5Cn.

Comment (lievenjanssen) [reply src/core/helpers/html/nl2br.ts:15]: Can this test be adjusted for it?https://github.com/xdan/jodit/blob/a0b42f22a50b9d8aceb2d8e241c1fbdae14a1e3c/test/tests/acceptance/clipboardTest.js#L1199-L1219

Comment (lievenjanssen) [reply src/core/helpers/html/nl2br.ts:15]: I suggest to already create a new jodit version which reverts the previous change or accepts this one to avoid putting the editor in a more broken state.
